version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: emna
      MONGO_INITDB_ROOT_PASSWORD: emna
